### ISSUE TITLE
Call to undefined method Zet\FileUpload\Model\UploadController::validate().

### ISSUE THREAD

**Issue by petroff007** [JZechy/jQuery-FileUpload#1]
PHP 5.3.5
Nette 2.3.10

Zatím bez požití vlastní modelové třídy pro upload
Zet\FileUpload\FileUploadControl::register($container);

Presenter

protected function createComponentZetMyForm() {

```
    $form = new \Nette\Application\UI\Form;
    $form->addFileUpload("uploader");

    $form->addSubmit('send', $this->template->txt['common']['ok'][$this->lang])
        ->setAttribute('class', 'btn btn-primary');

    $form->onValidate[] = $this->prodMgtZetMyFormValidate;
    $form->onSuccess[] = $this->prodMgtZetMyFormSucceeded;

return $form;
```

}

jQuery část pracuje perfektně. Po odeslání formuláře však hlásí:

Nette\MemberAccessException
Call to undefined method Zet\FileUpload\Model\UploadController::validate().
![uploadcontroller_validate_error](https://cloud.githubusercontent.com/assets/18551115/14636866/405c6708-062e-11e6-9ba9-bfab8eebb9a3.jpg)

Zdravím!

**Comment by JZechy** [comment]
Do controlleru byla přidána funkce validate(), aby to prošlo.
_Nicméně se bude muset vymyslet čistější řešení._
