### ISSUE TITLE
Non-static method Zet\FileUpload\FileUploadControl::setFileFilter()

### ISSUE THREAD

**Issue by ghost** [JZechy/jQuery-FileUpload#10]
In PHP 7.0 you can see error Non-static method Zet\FileUpload\FileUploadControl::setFileFilter() should not be called statically. You should use static in FileUploadControl.php 
line 275:  public **static** function setFileFilter($fileFilter)

**Comment by JZechy** [comment]
As I didn't read about this issue today with static in PHP 7... :D 

This was created by PR when there was try to call statically setFileFilter in bootstrap, to globally set up filter... 

So perhaps it's time to turn it back... And create registration of component as extension.

**Comment by ghost** [comment]
It would be nice to create and registrate it as extension.

**Comment by JZechy** [comment]
Component can be registrate as extension. FileFilter is not static anymore.
