### ISSUE TITLE
Chyba v dokumentaci

### ISSUE THREAD

**Issue by folpy** [JZechy/jQuery-FileUpload#11]
https://github.com/JZechy/jQuery-FileUpload/wiki/Instalace

je uvedena funkce getHead() ale ta neexistuje místo toho by tam mělo být getStyleSheet()

**Comment by JZechy** [comment]
Přepsáno :)

**Comment by JZechy** [comment]
Špatně... Metoda byla správně, tato metoda je ovšem k dispozici od verze 1.2.0-beta. Opraveno do původního stavu, teď už je 1.2.0 hlavní verzí.
