### ISSUE TITLE
Nette\Http\FileUpload - type is NULL

### ISSUE THREAD

**Issue by petroff007** [JZechy/jQuery-FileUpload#2]
Pokud obejdu předchozí issue s voláním UploadController::validate(). a dumpnu si obsah proměně $values, je typ souboru vždy NULL.

["type":"Nette\Http\FileUpload":private]=> NULL

Děkuji a zdravím!

**Comment by JZechy** [comment]
Tohle se asi moc mě týkat nebude, \Nette\Http\FileUpload si nijak type neplní, k jeho naplnění dochází až při zavolání [getContentType()](https://api.nette.org/2.3.10/source-Http.FileUpload.php.html#78-88).
