### ISSUE TITLE
Možnost rozšíření adresáře přes definování formuláře

### ISSUE THREAD

**Issue by hlavacz** [JZechy/jQuery-FileUpload#25]
Ještě bych přidal dynamickoku možnost definování cílové podsložky, ať se na každou podložku nemusí dělat jiný model. IUploadModel jsem rozšířil o setDirectory, který volám v handleRemove, handleRename a hlavně handleUpload. Zde to předám vlastnímu modelu a tam si to už vyřeším sám. UploadControlleru to předám přes FileUploadControl, kde jsem si přidal také funkci SetDirectory. Takže jednoduše při vytváření formuláře definuji, do které podložky v hlavní upload složce to chci nahrát. Hlavně bych to nemusel při každým Tvém updatu dopisovat :))

**Comment by JZechy** [comment]
Jestli chápu dobře, jde ti o to, že jiné uploadery mohou ukládat do jiných složek?

Můžeš na to využít fci setParams od v1.2.1, kdy si do pole nastavíš cílovou složku a v upload modelu si ji vytáhneš.

**Comment by hlavacz** [comment]
Vida, setParams si přidal chvíli po tom, co jsem to naimplementoval, což rozhodně vtipněji řeší mé potřeby :) Díky.
