### ISSUE TITLE
Přidání sekvenčního nahrávání do konfigurace

### ISSUE THREAD

**Issue by llsm** [JZechy/jQuery-FileUpload#27]
Navrhuji přidání možnosti `sequentialUploads: true` do konfigurace pluginu, ideálně už do neonu. Já jsem ho musel využít, protože jinak když se mi někdo pokusil nahrát 50 souborů a v jednu chvíli mi to vytvořilo 50 POSTů na server a snažilo se uploadovat, tak to většinou nestihli v časovém limitu apache a celý plugin skončil v křeči. Sekvenčně to funguje bez problémů. 

Díky za super práci

**Comment by JZechy** [comment]
Zašel jsem ještě dál, přidán atribute uploadSettings na uploaderu společně se setterem, getterem a add metodou pro přidání hodnoty do pole. Do něj lze nastavovat libovolné možnosti konfigurace blueimpova uploaderu dle vlastní potřeby.

Totéž přidáno i do konfigurace rozšíření.
