### ISSUE TITLE
Vícenásobný upload

### ISSUE THREAD

**Issue by JZechy** [JZechy/jQuery-FileUpload#33]
Pří výběru více souborů naráz neprojde kontrole na počet nahrávaných souborů.

https://forum.nette.org/cs/27287-jquery-fileupload-snadny-upload-souboru?p=3#p193902

**Comment by pitr82** [comment]
Ahoj, daří se ti to řešit?

**Comment by JZechy** [comment]
@pitr82 Ahoj, promin, ale k uploaderu jsem se ted dlouho nedostal.

**Comment by Attanon** [comment]
```
canUploadNextFile: function () {
	return this.uploaded < this.config.maxFiles || this.addedFiles < this.config.maxFiles;
},
```

Pravděpodobně se jedná o toto, proč je tam to || proč tam není &&, ono to projde tím, že uploaded = 0 když jich naklikneš víc najednou a tím pádem tahle podmínka projde i když je addedFiles víc jak maxFiles

**Comment by JZechy** [comment]
@Attanon Zkusil bys to napravit a poslat PR případně?

**Comment by KminekMatej** [comment]
Teď jsem si to opravil, moc se mi kvůli jednomu řádku nechce forkovat, nabízím tuto variantu:

> canUploadNextFile: function () {
		return this.addedFiles < this.config.maxFiles;
	},

**Comment by f3l1x** [comment]
Solved https://github.com/contributte/fileupload/pull/52

Kdyby byl problem, otevrete novou issue.
