### ISSUE TITLE
Verze pro Nette 3.0?

### ISSUE THREAD

**Issue by IJVo** [JZechy/jQuery-FileUpload#38]
Prosím, kdy bude verze pro Nette 3.0?

**Comment by lukyrys** [comment]
...\src\Model\UploadController.php:194
```
User Deprecated
Nette\Http\Request::getQuery() parameter $default is deprecated, use operator ??
```

**Comment by IJVo** [comment]
@lukyrys Opraveno zde https://github.com/IJVo/jQuery-FileUpload

**Comment by JosefRypacek** [comment]
Co udělat pull request do tohoto repa? Měl by o to @JZechy ještě zájem?

**Comment by IJVo** [comment]
@JosefRypacek  JZechy asi těžko, ten se neozývá. Můžeš to zkusit poslat ke mě, a já to zapracuji do své verze. Díky.

**Comment by JZechy** [comment]
Yup, pokud se @IJVo o knihovnu aktivně stará... Já se chystám oficiálně knihovnu předat 😃

**Comment by f3l1x** [comment]
Solved https://github.com/contributte/fileupload/pull/52
