### ISSUE TITLE
PHP 7.4 Deprecated: implode()

### ISSUE THREAD

**Issue by JosefRypacek** [JZechy/jQuery-FileUpload#41]
Po updatu na PHP 7.4 vyhazuje varování.

`PHP Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in ...vendor/jzechy/jquery-fileupload/src/Filter/BaseFilter.php:49
`

Pokud má @JZechy zájem, mohu připravit pull request.

**Comment by f3l1x** [comment]
Ahoj, zajem je.

**Comment by JosefRypacek** [comment]
Ahoj, zrovna jsem koukal, ze oprava implode jiz je zahrnuta v pull requestu pro nette 3.
Navíc jsem dle https://github.com/contributte/fileupload/issues/38 přepnul na fork od IJVo.
