### ISSUE TITLE
Not working jquery-FileUpload after ajax load form

### ISSUE THREAD

**Issue by pdomkar** [JZechy/jQuery-FileUpload#7]
Když se formulář s FileUpload načte pomocí ajaxu (překreslím snippet s formulářem) tak se nejspíš neinicializuje javascript nad inputem -> .fileupload(
Pokud stranku s formulářem obnovím tak se v souboru template/javascript.latte zavolá funkce `document.addEventListener("DOMContentLoaded", function(event) {` v které se nejspíš input inicializuje.

Pokud ale stranku načtu přes ajax tato funkce se neprovede. Následně se tedy otevře okno pro vyber souboru, ale jíž se nevykreslí a nepřidají.

**Comment by JZechy** [comment]
Aktuální stav master větvě se moc dobře ještě neozkoušel bohužel (proto s aktuálním stavem taky nevyšla nová verze). Problém se pokusím ovšem napravit, jak rychle to půjde.

Do té doby doporučuji stáhnout stable verzi 1.1.3, tam se ještě používat **$(function() {...});** A ten funguje bez problému.

**Comment by JZechy** [comment]
Opraveno ve verzi 1.1.4
