### ISSUE TITLE
User changes to control.latte

### ISSUE THREAD

**Issue by milsorm** [JZechy/jQuery-FileUpload#8]
I use your component in narrower column (col-md-9 instead of full col-md-10) and control.latte defines space for Choose files button too small in that conditions.

I cannot find a way how to change template via configuration so I have to create descendant which override getControl() and perform RE on original template.

But static method register() use **CLASS** so I need to copy this method to descendant for correct behaviour.

My recommendation:
- allow to change control.latte via configuration
- use something different than **CLASS** to determining current class name in register()

Thnx

**Comment by JZechy** [comment]
Hi,
I also get this problem on my last project. The only way now is, if you don't need more different templates, change control.latte as you need.

But about solution in next version. Version 1.2 will have several types of templates and setter for own template, if needed. And the default template will have some changes too. As I see, current layout isn't so perfect.

**Comment by milsorm** [comment]
I am looking for it :-)

**Comment by JZechy** [comment]
- Created two UI modes.
- Default full mode redesigned.
- For now without setter for own template.

**Comment by milsorm** [comment]
It works :-)
