### ISSUE TITLE
Custom template

### ISSUE THREAD

**Issue by milsorm** [JZechy/jQuery-FileUpload#9]
I add $templates array passed to addFileUpload() which is passed to model UploadController.

In this array I have pairs "ui mode" => "pathname for template".

When control file is searched for controller rendering and uiMode is different that your originals, I try to search in this array and use custom template (absolute/relative filename checking).

Works fine. I am not attaching pull request because this is very naive representation, but custom templates are very important in some projects so please add it to your roadmap.

**Comment by JZechy** [comment]
Done. Templates can be altered by setUiTemplate($uiMode, $filePath).
